# GitHub Pages Configuration

# Build settings
plugins:
  - jekyll-default-layout

# Exclude development files
exclude:
  - node_modules/
  - .github/
  - README.md

# Include all HTML, CSS, JS files
include:
  - index.html
  - script.js
  - styles.css
